# Generated by Django 4.2.7 on 2023-12-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_datasets_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification_Visualizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_type', models.CharField(choices=[('Pie Chart', 'Pie Chart'), ('Histogram', 'Histogram')], max_length=9)),
                ('dataset', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('x_data', models.TextField()),
                ('y_data', models.TextField()),
            ],
        ),
    ]
