# Generated by Django 4.2.7 on 2023-12-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_classification_visualizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification_visualizations',
            old_name='x_data',
            new_name='target_column',
        ),
        migrations.RemoveField(
            model_name='classification_visualizations',
            name='y_data',
        ),
    ]
