# Generated by Django 4.2.7 on 2023-12-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_x_data_classification_visualizations_target_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification_visualizations',
            name='target_column',
            field=models.CharField(max_length=255),
        ),
    ]
