# Generated by Django 4.2.7 on 2023-12-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_classification_visualizations_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vizualization_for_Regression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization_type', models.CharField(choices=[('Scatter Plot', 'Scatter Plot'), ('Violin Plot', 'Violin Plot')], max_length=12)),
                ('dataset', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('target_column_two', models.CharField(max_length=255)),
                ('target_column_one', models.CharField(max_length=255)),
            ],
        ),
    ]
