# Generated by Django 4.2.7 on 2023-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_vizualization_for_regression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=25)),
                ('model', models.FileField(upload_to='models/')),
                ('dataset', models.TextField()),
                ('model_type', models.CharField(max_length=15)),
                ('resampling_technique', models.IntegerField()),
                ('algorithm', models.IntegerField()),
                ('metric', models.IntegerField()),
            ],
        ),
    ]
