# Generated by Django 4.2.7 on 2023-12-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Trained_Models',
        ),
    ]
