# Generated by Django 4.2.7 on 2023-12-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_models_trained_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Trained_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=25)),
                ('model', models.FileField(upload_to='models/')),
                ('dataset_id', models.IntegerField()),
                ('model_type', models.CharField(max_length=15)),
                ('resampling_id', models.IntegerField()),
                ('algorithm_id', models.IntegerField()),
                ('metric_id', models.IntegerField()),
            ],
        ),
    ]
